name: Docker Image CI

on:
  create:
    tags: 
      - '*'
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
        name: Login to DockerHub
        env:
          DOKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOKERHUB_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        uses: docker/login-action@v1
        with:
          username: $DOKERHUB_USER
          password: $DOKERHUB_TOKEN
    -
       name: Build
       run: |
          docker build -f Dockerfile -t getcarrier/observer-browsertime:2.5 .
    -
       name: Push
       run: |
         docker push getcarrier/observer-browsertime:2.5
